### ISSUE TITLE
compile on macOS

### ISSUE THREAD

**Issue by grylem** [jasonbking/mancvt#1]
How i can compile it on macOS?
Thank.

**Comment by jasonbking** [comment]
I've pushed a change that should fix that.  BTW, I originally wrote this to help convert man pages on illumos to mdoc, so most of the code looks for common patterns found in illumos man pages and replaces them with mdoc equivalents.  The result usually still needs some manual editing, but hopefully far less than doing the whole thing by hand.

I have no idea how useful it'll be for man pages from other platforms, though feedback is welcome.
